### ISSUE TITLE
recent forum activity ignores forum permissions

### ISSUE THREAD

**Issue by osusoy** [bluethrust/clanscripts#15]
bug - this is fairly critical. basically, if a member doesn't have access to a forum then even the forum's existence is hidden from them which is most excellent but the forum activity box seems to completely ignore all forum settings and display any post to anyone including guests! so, even the most private of forum comments is partly visible to everyone. if one of those people clicks on the link than the app falls apart (description as reported to me). The box should only be showing forum activity for boards a user has at least read permission to.

**Comment by bluethrust** [comment]
I'm going to need more info on this one.  Would you be able to send me an admin login to test it out on your site?  I just tested it out on the demo site, using both rank wide access rules and individual and it seemed to work.  I will say that it might be incorrect wording on my part.  When you are setting the access, "All Members", that actually means everyone (including the public) can view it.  

You can test it out on the demo site.  If you go to http://bluethrust.com/cs4demo, the latest post should be "test attachment".  If you log in using testmember25 for username, 12345 for password, the latest post becomes "test post".  If you log in using testmember26, same password (who I've blocked access to this forum), you will see "test attachments" for the latest post.

**Comment by osusoy** [comment]
well if you do what i understand you did there then we are talking about a different topic. what i understand is that you have blocked access to testmember26 specifically which is not very useful as i would need to do that for every user every time they change ranks in a rank based permission system with a whole bunch of boards. what i am talking about is the activity box honoring forum settings without intervention. to test this on your site, don't set any special rules for testmember26 but assign him to a rank that doesn't have any read or write permissions for a forum and then see if they see posts they shouldn't in the activity box.

**Comment by osusoy** [comment]
btw, keep this on hold for a sec, i'll investigate it properly later.

**Comment by bluethrust** [comment]
Ok, just set testmember26 to a different rank that has no rules assigned to it and removed the individual access rules.  It still doesn't show the "test post" in the activity box.

**Comment by bluethrust** [comment]
ok no problem

**Comment by osusoy** [comment]
grr, i should have tested this myself first, too much trust in the member! i can't make it happen myself so closing this. i have also asked the member to try it again in case it is happening to him and not me (i am wired to the server). if he still reports a problem, i'll reopen this, otherwise, ignore. sorry for that.

**Comment by osusoy** [comment]
ok, i figured out what the member meant, i'll create a separate issue for it as its a tricky one
