### ISSUE TITLE
deleted comments hiding threads

### ISSUE THREAD

**Issue by osusoy** [bluethrust/clanscripts#17]
bug - just checked it myself as well. if someone with the permissions deletes a comment on a thread, they are presented with the error:

```
"Fatal error: Call to undefined method ForumPost::getPostAttachements() in /path/to/clanscripts/classes/forumpost.php on line 161"
```

the whole thread gets removed from the forum but is not actually deleted. although i can no longer see it in the forum, i can access it either through forum activity or by searching for it. Once I have accessed it, adding a new comment fixes the problem and the thread is listed in the forum once again with only the intended comment deleted. so it seems like a simple broken reference somewhere that gets corrected at next comment.

**Comment by osusoy** [comment]
btw, this is just a spelling mistake :/ are you using a different version for your hosted services?

**Comment by bluethrust** [comment]
No but I think I fixed this one should be fixed in the one on here and on the download

**Comment by osusoy** [comment]
hmm, need to link up repositories at some stage. will be a bit tricky as i am applying fixes to the version i initially downloaded. but, considering i am still doing this, will have a go when i find the time for it.
