### ISSUE TITLE
undefined value error handling in _functions.php

### ISSUE THREAD

**Issue by osusoy** [bluethrust/clanscripts#6]
btw, all these issues are from the version downloaded from the bluethrust website, i have no idea which revision of the code that corresponds to.

l179 

```
 if(trim($_SERVER['HTTPS']) || $_SERVER['HTTPS'] == "off") {
```

fails if the 'HTTPS' key is not in the object. this might be a configuration issue but is easily fixed with:

```
 if(isset($_SERVER['HTTPS']) && (trim($_SERVER['HTTPS']) || $_SERVER['HTTPS'] == "off")) {
```

**Comment by bluethrust** [comment]
ok fixed! thanks
