### ISSUE TITLE
unable to upload images

### ISSUE THREAD

**Issue by osusoy** [bluethrust/clanscripts#8]
· Unable to upload games image file. Please make sure the file extension is either .jpg, .png, .gif or .bmp

getting this for all of those formats. basically can't upload images for anything and there are is no output to error logs so this should be interesting

**Comment by osusoy** [comment]
this seems like a case of hardcoding directories. `members/include/admin/managerankcat/edit.php` (l153) is looking for the images directory in `../images` which is obviously the wrong location :/

**Comment by osusoy** [comment]
ok, easy fix but i guess it will need to be applied to every page with an image upload (!). when you are using BTUpload () (`members/include/admin/managerankcat/edit.php` l152 in this case), just change the directory from `../images/ranks/` to `$BASE_DIRECTORY."images/ranks/"` and all is well... well, for that case at least :/

**Comment by bluethrust** [comment]
Are you having this issue on the version that's downloaded from the site as well? It works on my copy using the ../

**Comment by osusoy** [comment]
that might be true for the way you expect the file structure to be but the whole thing falls apart if it isn't and it is a bad idea to hardcode paths in general, especially when the information is already available to you from the config.

i didn't need to do anything special there, `$BASE_DIRCTORY` was available and correctly populated already. by hardcoding the path in the code instead, you are basically just ignoring a configuration setting.

and the reason it works for you is that by looking at the code, you seem to assume files to be in a cs4 folder. in the repository, those files are in the root path and the installer doesn't create any symlinks? considering it works fine without that folder once i make this correction, the flexibility is built in already and just getting blocked by the hardcoding.

cheers

**Comment by bluethrust** [comment]
The cs4 is tied to the $MAIN_ROOT variable.  Running the installer figures out what the $MAIN_ROOT is.  If you change that to how your setup is (if it's just in the root, set that to a single forward slash), you should be able to use the way I had set it up.  I agree that BASE_DIRECTORY is probably better, but that variable was actually recently added and it hasn't been broken so it should work the way it is.

**Comment by osusoy** [comment]
well, i've said my piece and there were no questions in your response so the issue would normally be closed (just press "close and comment" instead of "comment") so it doesn't crowd up your open issues. a tip though; there are many advantages to open source but there are disadvantages as well. at the moment it seems to be just me using this place and i certainly don't have time to become competition. but, if you reject stuff that is useful to others and someone forks your repository and starts implementing that stuff, people start using their repository instead and the project sort of ends up becoming theirs; whichever repository gets used the most automatically becomes its true home.

if you agree with an issue but don't have time (your response reads like you agree but aren't going to change it now), just indicate that and maybe add some labels/milestones to the issue so you can keep track of it for later. In any case, all the issues i have reported are already fixed in my local repository, just giving back to the project here.

btw, you might want to try this exercise; you must have some classmates in your computer science course, ask one of them to install the software without giving them any instructions and observe them while they are doing it (quietly, no tips or instructions). that should give you a lot of useful information.

**Comment by osusoy** [comment]
btw, as developers, we just hear about the broken stuff but a big well done from me for the functionality. i can administer the site in character which is wonderful for a role playing group and it was fairly easy to create a new theme from one of the existing ones :) i also haven't run into any further problems with the core application. If you end up playing Elite one day, give me a yell, it is the only game the group plays (mostly a bunch of oldies that were hooked on the original from the 80s lol).

also, it might help to have your themes on github too. I did create a new theme based on BlueIce and fixed some issues along the way that also apply to the original BlueIce. for example, news ticker cuts out the bottom of letters such as g, j, q, y so needs more height.
